using System.Collections.Generic;

public class QuizzesLoader
{
    public static IList<Quiz> Quizzes => quizzes;

    private static IList<Quiz> quizzes = new List<Quiz>
    {
        new Quiz {Id = 1, Kanji = "一", Yomi = "いち"},
        new Quiz {Id = 2, Kanji = "右", Yomi = "みぎ"},
        new Quiz {Id = 3, Kanji = "雨", Yomi = "あめ"},
        new Quiz {Id = 4, Kanji = "円", Yomi = "えん"},
        new Quiz {Id = 5, Kanji = "王", Yomi = "おう"},
        new Quiz {Id = 6, Kanji = "音", Yomi = "おと"},
        new Quiz {Id = 7, Kanji = "下", Yomi = "した"},
        new Quiz {Id = 8, Kanji = "火", Yomi = "ひ"},
        new Quiz {Id = 9, Kanji = "花", Yomi = "はな"},
        new Quiz {Id = 10, Kanji = "貝", Yomi = "かい"},
        new Quiz {Id = 11, Kanji = "学", Yomi = "がく"},
        new Quiz {Id = 12, Kanji = "気", Yomi = "き"},
        new Quiz {Id = 13, Kanji = "九", Yomi = "きゅう"},
        new Quiz {Id = 14, Kanji = "休", Yomi = "きゅう"},
        new Quiz {Id = 15, Kanji = "玉", Yomi = "たま"},
        new Quiz {Id = 16, Kanji = "金", Yomi = "かね"},
        new Quiz {Id = 17, Kanji = "空", Yomi = "そら"},
        new Quiz {Id = 18, Kanji = "月", Yomi = "つき"},
        new Quiz {Id = 19, Kanji = "犬", Yomi = "いぬ"},
        new Quiz {Id = 20, Kanji = "見", Yomi = "けん"},
        new Quiz {Id = 21, Kanji = "五", Yomi = "ご"},
        new Quiz {Id = 22, Kanji = "口", Yomi = "くち"},
        new Quiz {Id = 23, Kanji = "校", Yomi = "こう"},
        new Quiz {Id = 24, Kanji = "左", Yomi = "ひだり"},
        new Quiz {Id = 25, Kanji = "三", Yomi = "さん"},
        new Quiz {Id = 26, Kanji = "山", Yomi = "やま"},
        new Quiz {Id = 27, Kanji = "子", Yomi = "こ"},
        new Quiz {Id = 28, Kanji = "四", Yomi = "よん"},
        new Quiz {Id = 29, Kanji = "糸", Yomi = "いと"},
        new Quiz {Id = 30, Kanji = "字", Yomi = "じ"},
        new Quiz {Id = 31, Kanji = "耳", Yomi = "みみ"},
        new Quiz {Id = 32, Kanji = "七", Yomi = "なな"},
        new Quiz {Id = 33, Kanji = "車", Yomi = "くるま"},
        new Quiz {Id = 34, Kanji = "手", Yomi = "て"},
        new Quiz {Id = 35, Kanji = "十", Yomi = "じゅう"},
        new Quiz {Id = 36, Kanji = "出", Yomi = "しゅつ"},
        new Quiz {Id = 37, Kanji = "女", Yomi = "おんな"},
        new Quiz {Id = 38, Kanji = "小", Yomi = "しょう"},
        new Quiz {Id = 39, Kanji = "上", Yomi = "うえ"},
        new Quiz {Id = 40, Kanji = "森", Yomi = "もり"},
        new Quiz {Id = 41, Kanji = "人", Yomi = "ひと"},
        new Quiz {Id = 42, Kanji = "水", Yomi = "みず"},
        new Quiz {Id = 43, Kanji = "正", Yomi = "せい"},
        new Quiz {Id = 44, Kanji = "生", Yomi = "せい"},
        new Quiz {Id = 45, Kanji = "青", Yomi = "あお"},
        new Quiz {Id = 46, Kanji = "夕", Yomi = "ゆう"},
        new Quiz {Id = 47, Kanji = "石", Yomi = "いし"},
        new Quiz {Id = 48, Kanji = "赤", Yomi = "あか"},
        new Quiz {Id = 49, Kanji = "千", Yomi = "せん"},
        new Quiz {Id = 50, Kanji = "川", Yomi = "かわ"},
        new Quiz {Id = 51, Kanji = "先", Yomi = "さき"},
        new Quiz {Id = 52, Kanji = "早", Yomi = "そう"},
        new Quiz {Id = 53, Kanji = "草", Yomi = "くさ"},
        new Quiz {Id = 54, Kanji = "足", Yomi = "あし"},
        new Quiz {Id = 55, Kanji = "村", Yomi = "むら"},
        new Quiz {Id = 56, Kanji = "大", Yomi = "だい"},
        new Quiz {Id = 57, Kanji = "男", Yomi = "おとこ"},
        new Quiz {Id = 58, Kanji = "竹", Yomi = "たけ"},
        new Quiz {Id = 59, Kanji = "中", Yomi = "なか"},
        new Quiz {Id = 60, Kanji = "虫", Yomi = "むし"},
        new Quiz {Id = 61, Kanji = "町", Yomi = "まち"},
        new Quiz {Id = 62, Kanji = "天", Yomi = "てん"},
        new Quiz {Id = 63, Kanji = "田", Yomi = "た"},
        new Quiz {Id = 64, Kanji = "土", Yomi = "つち"},
        new Quiz {Id = 65, Kanji = "二", Yomi = "に"},
        new Quiz {Id = 66, Kanji = "日", Yomi = "ひ"},
        new Quiz {Id = 67, Kanji = "入", Yomi = "にゅう"},
        new Quiz {Id = 68, Kanji = "年", Yomi = "とし"},
        new Quiz {Id = 69, Kanji = "白", Yomi = "しろ"},
        new Quiz {Id = 70, Kanji = "八", Yomi = "はち"},
        new Quiz {Id = 71, Kanji = "百", Yomi = "ひゃく"},
        new Quiz {Id = 72, Kanji = "文", Yomi = "ぶん"},
        new Quiz {Id = 73, Kanji = "木", Yomi = "き"},
        new Quiz {Id = 74, Kanji = "本", Yomi = "ほん"},
        new Quiz {Id = 75, Kanji = "名", Yomi = "な"},
        new Quiz {Id = 76, Kanji = "目", Yomi = "め"},
        new Quiz {Id = 77, Kanji = "立", Yomi = "りつ"},
        new Quiz {Id = 78, Kanji = "力", Yomi = "ちから"},
        new Quiz {Id = 79, Kanji = "林", Yomi = "はやし"},
        new Quiz {Id = 80, Kanji = "六", Yomi = "ろく"},
    };
}